################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
OBJS := 
C_DEPS := 
EXECUTABLES := 

# Every subdirectory with source files must be described here
SUBDIRS := \
test \
ssl \
ms \
fips/utl \
fips/sha \
fips/rsa \
fips/rand \
fips/hmac \
fips \
fips/ecdsa \
fips/ecdh \
fips/dsa \
fips/dh \
fips/des \
fips/cmac \
fips/aes \
engines \
engines/ccgost \
demos/x509 \
demos/tunala \
demos/state_machine \
demos \
demos/smime \
demos/sign \
demos/prime \
demos/pkcs12 \
demos/maurice \
demos/engines/zencod \
demos/engines/rsaref \
demos/engines/ibmca \
demos/engines/cluster_labs \
demos/eay \
demos/easy_tls \
demos/cms \
demos/bio \
demos/asn1 \
crypto/x509v3 \
crypto/x509 \
crypto/whrlpool \
crypto \
crypto/ui \
crypto/txt_db \
crypto/ts \
crypto/threads \
crypto/store \
crypto/stack \
crypto/srp \
crypto/sha \
crypto/seed \
crypto/rsa \
crypto/ripemd \
crypto/rc5 \
crypto/rc4 \
crypto/rc2 \
crypto/rand \
crypto/pqueue \
crypto/pkcs7 \
crypto/pkcs12 \
crypto/pem \
crypto/ocsp \
crypto/objects \
crypto/modes \
crypto/mdc2 \
crypto/md5 \
crypto/md5/asm \
crypto/md4 \
crypto/md2 \
crypto/lhash \
crypto/krb5 \
crypto/jpake \
crypto/idea \
crypto/hmac \
crypto/evp \
crypto/err \
crypto/engine \
crypto/ecdsa \
crypto/ecdh \
crypto/ec \
crypto/dso \
crypto/dsa \
crypto/dh \
crypto/des \
crypto/conf \
crypto/comp \
crypto/cms \
crypto/cmac \
crypto/cast \
crypto/camellia \
crypto/buffer \
crypto/bn \
crypto/bn/asm \
crypto/bio \
crypto/bf \
crypto/asn1 \
crypto/aes/asm \
crypto/aes \
bugs \
apps \

